In [ ]:
Aim: Linear Regression by using Deep Neural Network
In [ ]:
In [1]:
In [2]:
In [3]:
In [4]:
In [5]:
In [6]:
In [7]:
In [8]:
(404, 13)
(102, 13)
(404,)
(102,)
Out[4]: array([ 1.23247, 0. , 8.14 , 0. , 0.538 , 6.142 ,
 91.7 , 3.9769 , 4. , 307. , 21. , 396.9 ,
 18.72 ])
Out[5]: 15.2
Out[7]: array([0.0024119 , 0. , 0.01592969, 0. , 0.00105285,
 0.01201967, 0.17945359, 0.00778265, 0.00782786, 0.6007879 ,
 0.04109624, 0.77671895, 0.03663436])
Out[8]: 15.2
pip install tensorflow --user --no-warn-script-location
import tensorflow as tf
from tensorflow.keras.datasets import boston_housing
from sklearn import preprocessing
(train_x, train_y),(test_x,test_y)=boston_housing.load_data()
print(train_x.shape)
print(test_x.shape)
print(train_y.shape)
print(test_y.shape)
train_x[0]
train_y[0]
train_x=preprocessing.normalize(train_x)
test_x=preprocessing.normalize(test_x)
train_x[0]
train_y[0]
In [9]:
In [10]:
In [11]:
In [12]:
Epoch 1/100
404/404 [==============================] - 1s 2ms/step - loss: 145.2648 -
mae: 8.8432 - val_loss: 70.4067 - val_mae: 6.0675
Epoch 2/100
404/404 [==============================] - 2s 4ms/step - loss: 69.6452 -
mae: 5.8083 - val_loss: 60.2890 - val_mae: 5.7936
Epoch 3/100
404/404 [==============================] - 2s 4ms/step - loss: 64.0329 -
mae: 5.4785 - val_loss: 58.2462 - val_mae: 5.5318
Epoch 4/100
404/404 [==============================] - 2s 4ms/step - loss: 62.4070 -
mae: 5.4575 - val_loss: 55.6510 - val_mae: 5.6276
Epoch 5/100
404/404 [==============================] - 1s 4ms/step - loss: 57.9584 -
mae: 5.3383 - val_loss: 54.0462 - val_mae: 5.4752
Epoch 6/100
404/404 [==============================] - 1s 3ms/step - loss: 58.4756 -
mae: 5.2441 - val_loss: 61.6325 - val_mae: 5.5175
Epoch 7/100
404/404 [ ] 2s 4ms/step loss: 55 2975
Actual output : 15.2
1/1 [==============================] - 0s 105ms/step
Predicted output: [[15.099294]]
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
def HPPM():
 model=Sequential()
 model.add(Dense(128, activation='relu', input_shape=(train_x[0].shape)))
 model.add(Dense(64, activation='relu'))
 model.add(Dense(32, activation='relu'))
 model.add(Dense(1))
 model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
 return model
import numpy as np
k=4
num_val_samples=len(train_x)
num_epochs=100
all_scores=[]
model=HPPM()
history=model.fit(x=train_x, y=train_y, epochs=num_epochs, batch_size=1, verbo
test_input=[(8.65407330e-05, 0.00000000e+00, 1.13392175e-02, 0.00000000e+00, 1
print("Actual output : 15.2")
print("Predicted output: ", model.predict(test_input))

In [ ]:
Aim: Classification using Deep Neural Network
In [1]:
In [2]:
In [3]:
In [4]:
In [5]:
In [6]:
Review is [1, 778, 128, 74, 12, 630, 163, 15, 4, 1766, 7982, 1051, 2, 32, 8
5, 156, 45, 40, 148, 139, 121, 664, 665, 10, 10, 1361, 173, 4, 749, 2, 16, 3
804, 8, 4, 226, 65, 12, 43, 127, 24, 2, 10, 10]
Review is 0
{'fawn': 34701, 'tsukino': 52006, 'nunnery': 52007, 'sonja': 16816, 'van
i': 63951, 'woods': 1408, 'spiders': 16115, 'hanging': 2345, 'woody': 228
9, 'trawling': 52008, "hold's": 52009, 'comically': 11307, 'localized': 4
0830, 'disobeying': 30568, "'royale": 52010, "harpo's": 40831, 'canet': 5
2011, 'aileen': 19313, 'acurately': 52012, "diplomat's": 52013, 'rickma
n': 25242, 'arranged': 6746, 'rumbustious': 52014, 'familiarness': 52015,
"spider'": 52016, 'hahahah': 68804, "wood'": 52017, 'transvestism': 4083
3, "hangin'": 34702, 'bringing': 2338, 'seamier': 40834, 'wooded': 34703,
'bravora': 52018, 'grueling': 16817, 'wooden': 1636, 'wednesday': 16818,
"'prix": 52019, 'altagracia': 34704, 'circuitry': 52020, 'crotch': 11585,
'busybody': 57766, "tart'n'tangy": 52021, 'burgade': 14129, 'thrace': 520
23, "tom's": 11038, 'snuggles': 52025, 'francesco': 29114, 'complainers':
52027, 'templarios': 52125, '272': 40835, '273': 52028, 'zaniacs': 52130,
'275': 34706, 'consenting': 27631, 'snuggled': 40836, 'inanimate': 15492,
'uality': 52030, 'bronte': 11926, 'errors': 4010, 'dialogs': 3230, "yomad
a's": 52031, "madman's": 34707, 'dialoge': 30585, 'usenet': 52033, 'video
drome': 40837, "kid'": 26338, 'pawed': 52034, "'girlfriend'": 30569, "'pl
easure": 52035, "'reloaded'": 52036, "kazakos'": 40839, 'rocque': 52037,
'mailings': 52038, 'brainwashed': 11927, 'mcanally': 16819, "tom''": 5203
9 'k t' 25243 ' ffili t d' 21905 'b b h' 52040 " ' " 4
Out[5]: (25000,)
Out[6]: (25000,)
import numpy as np
import pandas as pd
from keras.datasets import imdb
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000) 
data = np.concatenate((X_train, X_test), axis=0)
label = np.concatenate((y_train, y_test), axis=0)
print("Review is ",X_train[5]) 
print("Review is ",y_train[5])
vocab=imdb.get_word_index() 
print(vocab) 
X_train.shape
X_test.shape
In [7]:
In [8]:
In [9]:
In [10]:
In [11]:
In [12]:
In [13]:
Out[7]: array([1, 0, 0, ..., 0, 1, 0], dtype=int64)
Out[8]: array([0, 1, 1, ..., 0, 0, 0], dtype=int64)
Out[11]: array([1, 0, 0, ..., 1, 0, 0], dtype=int64)
Label: 1
[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 3
6, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 17
2, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 1
92, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12,
16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2,
5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4,
130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12,
215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2,
7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13,
104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 22
6, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25,
104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 1
5, 16, 5345, 19, 178, 32]
y_train
y_test
def vectorize(sequences, dimension = 10000):
 # Create an all-zero matrix of shape (len(sequences), dimension)
 results = np.zeros((len(sequences), dimension))
 for i, sequence in enumerate(sequences):
 results[i, sequence] = 1
 return results
test_x = data[:10000]
test_y = label[:10000]
train_x = data[10000:]
train_y = label[10000:]
test_y
print("Label:", label[0])
print(data[0])
In [14]:
In [15]:
# this film was just brilliant casting location scenery story direction ever
yone's really suited the part they played and you could just imagine being t
here robert # is an amazing actor and now the same being director # father c
ame from the same scottish island as myself so i loved the fact there was a
real connection with this film the witty remarks throughout the film were gr
eat it was just brilliant so much that i bought the film as soon as it was r
eleased for # and would recommend it to everyone to watch and the fly fishin
g was amazing really cried at the end it was so sad and you know what they s
ay if you cry at a film it must have been good and this definitely was also
# to the two little boy's that played the # of norman and paul they were jus
t brilliant children are often left out of the # list i think because the st
ars that play them all grown up are such a big profile for the whole film bu
t these children are amazing and should be praised for what they have done d
on't you think the whole story was so lovely because it was true and was som
eone's life after all that was shared with us all
Out[15]: {'fawn': 34701,
'tsukino': 52006,
'nunnery': 52007,
'sonja': 16816,
'vani': 63951,
'woods': 1408,
'spiders': 16115,
'hanging': 2345,
'woody': 2289,
'trawling': 52008,
"hold's": 52009,
'comically': 11307,
'localized': 40830,
'disobeying': 30568,
"'royale": 52010,
"harpo's": 40831,
'canet': 52011,
'aileen': 19313,
'acurately': 52012,
"diplomat's": 52013
index = imdb.get_word_index()
reverse_index = dict([(value, key) for (key, value) in index.items()]) 
decoded = " ".join( [reverse_index.get(i - 3, "#") for i in data[0]] ) 
print(decoded) 
index
In [16]:
In [17]:
In [18]:
In [19]:
In [20]:
Out[16]: {34701: 'fawn',
52006: 'tsukino',
52007: 'nunnery',
16816: 'sonja',
63951: 'vani',
1408: 'woods',
16115: 'spiders',
2345: 'hanging',
2289: 'woody',
52008: 'trawling',
52009: "hold's",
11307: 'comically',
40830: 'localized',
30568: 'disobeying',
52010: "'royale",
40831: "harpo's",
52011: 'canet',
19313: 'aileen',
52012: 'acurately',
52013 "di l t' "
Out[17]: "# this film was just brilliant casting location scenery story direction eve
ryone's really suited the part they played and you could just imagine being
there robert # is an amazing actor and now the same being director # father
came from the same scottish island as myself so i loved the fact there was a
real connection with this film the witty remarks throughout the film were gr
eat it was just brilliant so much that i bought the film as soon as it was r
eleased for # and would recommend it to everyone to watch and the fly fishin
g was amazing really cried at the end it was so sad and you know what they s
ay if you cry at a film it must have been good and this definitely was also
# to the two little boy's that played the # of norman and paul they were jus
t brilliant children are often left out of the # list i think because the st
ars that play them all grown up are such a big profile for the whole film bu
t these children are amazing and should be praised for what they have done d
on't you think the whole story was so lovely because it was true and was som
eone's life after all that was shared with us all"
Out[20]: (40000, 10000)
reverse_index
decoded
data = vectorize(data)
label = np.array(label).astype("float32")
# Creating train and test data set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data,label, test_size=0.20
X_train.shape
In [21]:
In [22]:
In [23]:
In [24]:
Out[21]: (10000, 10000)
Model: "sequential"
_________________________________________________________________
Layer (type) Output Shape Param # 
=================================================================
dense (Dense) (None, 50) 500050 
 
dropout (Dropout) (None, 50) 0 
dense_1 (Dense) (None, 50) 2550 
dropout_1 (Dropout) (None, 50) 0 
dense_2 (Dense) (None, 50) 2550 
dense_3 (Dense) (None, 1) 51 
=================================================================
Total params: 505,201
Trainable params: 505,201
Non-trainable params: 0
_________________________________________________________________
X_test.shape
from keras.utils import to_categorical
from keras import models
from keras import layers
model = models.Sequential()
# Input - Layer
model.add(layers.Dense(50, activation = "relu", input_shape=(10000, )))
# Hidden - Layers
model.add(layers.Dropout(0.3, noise_shape=None, seed=None))
model.add(layers.Dense(50, activation = "relu")) #ReLU" stands for Rectified L
model.add(layers.Dropout(0.2, noise_shape=None, seed=None))
model.add(layers.Dense(50, activation = "relu"))
# Output- Layer
model.add(layers.Dense(1, activation = "sigmoid")) #adds another Dense layer t
model.summary()
import tensorflow as tf
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=3)
In [25]:
In [26]:
In [27]:
In [28]:
Epoch 1/2
80/80 [==============================] - 5s 46ms/step - loss: 0.4119 - accur
acy: 0.8105 - val_loss: 0.2616 - val_accuracy: 0.8968
Epoch 2/2
80/80 [==============================] - 3s 38ms/step - loss: 0.2191 - accur
acy: 0.9158 - val_loss: 0.2548 - val_accuracy: 0.8989
0.897849977016449
313/313 [==============================] - 1s 3ms/step
Out[28]: array([[0.1319962 ],
 [0.9938973 ],
 [0.8705446 ],
 ...,
 [0.95068085],
 [0.9893535 ],
 [0.99133193]], dtype=float32)
model.compile(
optimizer = "adam",
loss = "binary_crossentropy",
metrics = ["accuracy"]
)
results = model.fit(
X_train, y_train,
epochs= 2,
batch_size = 500,
validation_data = (X_test, y_test),
callbacks=[callback]
) 
print(np.mean(results.history["val_accuracy"])) 
model.predict(X_test)

In [ ]:
Aim: Convolutional Neural Network (CNN)
In [1]:
In [2]:
In [3]:
In [4]:
In [5]:
In [6]:
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-dat
asets/train-labels-idx1-ubyte.gz (https://storage.googleapis.com/tensorflow/
tf-keras-datasets/train-labels-idx1-ubyte.gz)
29515/29515 [==============================] - 0s 2us/step
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-dat
asets/train-images-idx3-ubyte.gz (https://storage.googleapis.com/tensorflow/
tf-keras-datasets/train-images-idx3-ubyte.gz)
26421880/26421880 [==============================] - 176s 7us/step
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-dat
asets/t10k-labels-idx1-ubyte.gz (https://storage.googleapis.com/tensorflow/t
f-keras-datasets/t10k-labels-idx1-ubyte.gz)
5148/5148 [==============================] - 0s 0s/step
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-dat
asets/t10k-images-idx3-ubyte.gz (https://storage.googleapis.com/tensorflow/t
f-keras-datasets/t10k-images-idx3-ubyte.gz)
4422102/4422102 [==============================] - 8s 2us/step
Out[3]: (60000, 28, 28, 1)
Out[4]: (10000, 28, 28, 1)
Out[5]: (60000,)
Out[6]: (10000,)
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow import keras
import numpy as np
(x_train, y_train), (x_test, y_test) = keras.datasets.fashion_mnist.load_data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)
x_train.shape
x_test.shape
y_train.shape
y_test.shape
In [7]: model = keras.Sequential([
 keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
 keras.layers.MaxPooling2D((2,2)),
 keras.layers.Dropout(0.25),
 keras.layers.Conv2D(64, (3,3), activation='relu'),
 keras.layers.MaxPooling2D((2,2)),
 keras.layers.Dropout(0.25),
 
 keras.layers.Conv2D(128, (3,3), activation='relu'),
 keras.layers.Flatten(),
 keras.layers.Dense(128, activation='relu'),
 keras.layers.Dropout(0.25),
 keras.layers.Dense(10, activation='softmax')
])
In [8]:
In [10]:
Model: "sequential"
_________________________________________________________________
Layer (type) Output Shape Param # 
=================================================================
conv2d (Conv2D) (None, 26, 26, 32) 320 
 
max_pooling2d (MaxPooling2D (None, 13, 13, 32) 0 
) 
dropout (Dropout) (None, 13, 13, 32) 0 
conv2d_1 (Conv2D) (None, 11, 11, 64) 18496 
max_pooling2d_1 (MaxPooling (None, 5, 5, 64) 0 
2D) 
dropout_1 (Dropout) (None, 5, 5, 64) 0 
conv2d_2 (Conv2D) (None, 3, 3, 128) 73856 
flatten (Flatten) (None, 1152) 0 
dense (Dense) (None, 128) 147584 
dropout_2 (Dropout) (None, 128) 0 
dense_1 (Dense) (None, 10) 1290 
=================================================================
Total params: 241,546
Trainable params: 241,546
Non-trainable params: 0
_________________________________________________________________
Epoch 1/3
1875/1875 [==============================] - 46s 24ms/step - loss: 0.4153 -
accuracy: 0.8474 - val_loss: 0.3430 - val_accuracy: 0.8802
Epoch 2/3
1875/1875 [==============================] - 46s 24ms/step - loss: 0.3342 -
accuracy: 0.8773 - val_loss: 0.3052 - val_accuracy: 0.8883
Epoch 3/3
1875/1875 [==============================] - 45s 24ms/step - loss: 0.3038 -
accuracy: 0.8875 - val_loss: 0.2720 - val_accuracy: 0.8999
model.summary()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metric
history = model.fit(x_train, y_train, epochs=3, validation_data=(x_test, y_te
In [11]:
313/313 [==============================] - 2s 7ms/step - loss: 0.2720 - accu
racy: 0.8999
Test accuracy: 0.8999000191688538
test_loss, test_acc = model.evaluate(x_test, y_test)
print('Test accuracy:', test_acc)